language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer install --dev
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u travis -ptravis -e 'create database scriptverifier;'
  - mysql -u travis -ptravis scriptverifier < res/logging.sql


script: ./vendor/bin/phpunit -c phpunit.xml